version: 6
networks:
  base:
    rpcs:
      - https://mainnet.base.org
      - https://base.drpc.org
      - https://base-rpc.publicnode.com
      - https://developer-access-mainnet.base.org
    chain-id: 8453
    network-id: 8453
    currency: ETH
  ethereum:
    rpcs:
      - https://ethereum-rpc.publicnode.com
      - https://eth.drpc.org
    chain-id: 1
    network-id: 1
    currency: ETH
  hyperevm:
    rpcs:
      - https://rpc.hyperliquid.xyz/evm
    chain-id: 999
    network-id: 999
    currency: HYPE
subgraphs:
  base: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/raindex-base/0xe522cB4a5fCb2eb31a52Ff41a4653d85A4fd7C9D-8e9477b/gn
  sft-base: https://api.goldsky.com/api/public/project_cmjr2df7svg6t01tl2ic706ao/subgraphs/sft-base/1.0.14/gn
  sft-ethereum: https://api.goldsky.com/api/public/project_cmjr2df7svg6t01tl2ic706ao/subgraphs/sft-mainnet/1.0.14/gn
  sft-hyperevm: https://api.goldsky.com/api/public/project_cmjr2df7svg6t01tl2ic706ao/subgraphs/sft-hyperevm/bac8721f59eac2e49c3379fecfac925a07a80da8/gn
metaboards:
  base: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/metadata-base/2025-07-06-594f/gn
raindexes:
  base:
    address: 0xe522cB4a5fCb2eb31a52Ff41a4653d85A4fd7C9D
    network: base
    subgraph: base
    deployment-block: 41747644
    local-db-remote: raindex
rainlangs:
  base:
    address: 0x22508460712C350e914b49155982d3A92D923b10
    network: base
local-db-remotes:
  raindex: https://raindex-bootstrap-db.lon1.digitaloceanspaces.com/local-db-manifests/1779881382550/manifest.yaml
local-db-sync:
  base:
    batch-size: 50
    max-concurrent-batches: 1
    retry-attempts: 3
    retry-delay-ms: 1000
    rate-limit-delay-ms: 5000
    finality-depth: 4
    bootstrap-block-threshold: 300
    sync-interval-ms: 5000
using-tokens-from:
  - https://raw.githubusercontent.com/ST0x-Technology/st0x.registry/203a6bd72f39eddc1a45fd07f997087d76a303cb/token-lists/base.json
  - https://raw.githubusercontent.com/ST0x-Technology/st0x.registry/9a05a77c6bee14963560d687c5a02b2d598de40e/token-lists/base-quotes.json
  - https://raw.githubusercontent.com/ST0x-Technology/st0x.registry/ff6fcc75bfea9ffcf8d0d17e808b0b0feb03d3ec/token-lists/ethereum.json
  - https://raw.githubusercontent.com/ST0x-Technology/st0x.registry/ff6fcc75bfea9ffcf8d0d17e808b0b0feb03d3ec/token-lists/hyperevm.json
